// Export functionality for challenges progress and analytics
export class ChallengeExporter {
  constructor() {
    this.progressData = null;
    this.analyticsEvents = [];
  }

  // Initialize with data
  async initialize(progressData, analyticsEvents = []) {
    this.progressData = progressData;
    this.analyticsEvents = analyticsEvents;
  }

  // Export progress data
  exportProgress(format = 'pdf') {
    if (!this.progressData) {
      console.error('No progress data available for export');
      return;
    }

    if (format === 'pdf') {
      this.exportProgressPDF();
    } else if (format === 'csv') {
      this.exportProgressCSV();
    } else if (format === 'json') {
      this.exportProgressJSON();
    }
  }

  exportProgressPDF() {
    const { jsPDF } = window.jspdf || {};
    if (!jsPDF) {
      // Fallback to CSV if PDF library not available
      console.warn('jsPDF library not available, falling back to CSV');
      this.exportProgressCSV();
      return;
    }

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    const margin = 20;
    const usableWidth = pageWidth - (margin * 2);

    // Title
    doc.setFontSize(20);
    doc.setFont(undefined, 'bold');
    doc.text('Challenges Dashboard Report', margin, 30);

    // Date
    doc.setFontSize(12);
    doc.setFont(undefined, 'normal');
    doc.text(`Generated: ${new Date().toLocaleString()}`, margin, 50);

    // Overview section
    doc.setFontSize(16);
    doc.setFont(undefined, 'bold');
    doc.text('Progress Overview', margin, 70);

    doc.setFontSize(11);
    doc.setFont(undefined, 'normal');

    const overview = this.progressData.overview;
    const yPos = 90;
    const lineHeight = 7;

    doc.text(`Total Challenges: ${overview.totalChallenges}`, margin, yPos);
    doc.text(`Completed: ${overview.completed}`, margin, yPos + lineHeight);
    doc.text(`Completion Rate: ${overview.completionRate}%`, margin, yPos + lineHeight * 2);
    doc.text(`Current Streak: ${overview.streak} days`, margin, yPos + lineHeight * 3);

    // Program breakdown
    doc.text('Program Breakdown:', margin, yPos + lineHeight * 5);
    doc.setFont(undefined, 'bold');
    
    const programs = this.progressData.programs;
    let currentY = yPos + lineHeight * 6;
    
    Object.entries(programs).forEach(([program, data]) => {
      doc.setFont(undefined, 'bold');
      doc.text(`${data.name} Challenges:`, margin, currentY);
      
      doc.setFont(undefined, 'normal');
      doc.text(`  Total: ${data.total}`, margin, currentY + lineHeight);
      doc.text(`  Completed: ${data.completed}`, margin, currentY + lineHeight);
      doc.text(`  Progress: ${data.percentage}%`, margin, currentY + lineHeight);
      
      if (data.recentActivity.length > 0) {
        doc.text(`  Recent Activity: ${data.recentActivity[0]}`, margin, currentY + lineHeight);
      }
      
      currentY += lineHeight * 5;
    });

    // Footer
    doc.setFontSize(10);
    doc.text(`Report generated by Challenges Dashboard - ${new Date().toISOString()}`, margin, currentY + 20);

    // Save PDF
    doc.save('challenges-progress-report.pdf');
  }

  exportProgressCSV() {
    const csvContent = this.generateProgressCSV();
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `challenges-progress-${new Date().toISOString().split('T')[0]}.csv`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  exportProgressJSON() {
    const jsonContent = JSON.stringify(this.progressData, null, 2);
    const blob = new Blob([jsonContent], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `challenges-progress-${new Date().toISOString().split('T')[0]}.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  generateProgressCSV() {
    const overview = this.progressData.overview;
    const programs = this.progressData.programs;
    
    // CSV Headers
    const headers = [
      'Category',
      'Program',
      'Total Challenges',
      'Completed',
      'Remaining',
      'Percentage',
      'Last Activity'
    ];

    // CSV Data Rows
    const rows = [
      ['Overview', 'All Programs', overview.totalChallenges, overview.completed, 
       overview.totalChallenges - overview.completed, overview.completionRate + '%', 'N/A'],
      
      ['Linux', programs.linux.name, programs.linux.total, programs.linux.completed,
       programs.linux.total - programs.linux.completed, programs.linux.percentage + '%', 
       programs.linux.recentActivity[0] || 'N/A'],
      
      ['Docker', programs.docker.name, programs.docker.total, programs.docker.completed,
       programs.docker.total - programs.docker.completed, programs.docker.percentage + '%', 
       programs.docker.recentActivity[0] || 'N/A'],
      
      ['DevOps', programs.devops.name, programs.devops.total, programs.devops.completed,
       programs.devops.total - programs.devops.completed, programs.devops.percentage + '%', 
       programs.devops.recentActivity[0] || 'N/A']
    ];

    // Convert to CSV string
    const csvContent = [
      headers.join(','),
      ...rows.map(row => row.join(','))
    ].join('\n');

    return csvContent;
  }

  // Export analytics events
  exportAnalytics(format = 'csv') {
    if (this.analyticsEvents.length === 0) {
      console.warn('No analytics events to export');
      return;
    }

    if (format === 'pdf') {
      this.exportAnalyticsPDF();
    } else if (format === 'json') {
      this.exportAnalyticsJSON();
    } else {
      this.exportAnalyticsCSV();
    }
  }

  exportAnalyticsPDF() {
    const { jsPDF } = window.jspdf || {};
    if (!jsPDF) {
      console.warn('jsPDF library not available for PDF export');
      return;
    }

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    const margin = 20;

    // Title
    doc.setFontSize(18);
    doc.setFont(undefined, 'bold');
    doc.text('Analytics Report', margin, 30);

    // Date range
    doc.setFontSize(12);
    doc.setFont(undefined, 'normal');
    doc.text(`Report Period: ${this.getDateRange()}`, margin, 50);
    doc.text(`Generated: ${new Date().toLocaleString()}`, margin, 60);

    // Events summary
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.text('Events Summary', margin, 80);

    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    
    const summary = this.getEventsSummary();
    const currentY = 90;
    const lineHeight = 6;

    doc.text(`Total Events: ${summary.totalEvents}`, margin, currentY);
    doc.text(`Page Views: ${summary.pageViews}`, margin, currentY + lineHeight);
    doc.text(`Button Clicks: ${summary.buttonClicks}`, margin, currentY + lineHeight * 2);
    doc.text(`Data Refreshes: ${summary.refreshCount}`, margin, currentY + lineHeight * 3);
    doc.text(`Avg Session Duration: ${Math.round(summary.avgSessionDuration / 1000 / 60)} minutes`, margin, currentY + lineHeight * 4);

    // Detailed events
    doc.setFontSize(12);
    doc.setFont(undefined, 'bold');
    doc.text('Recent Events (Last 50):', margin, currentY + lineHeight * 6);

    doc.setFontSize(9);
    doc.setFont(undefined, 'normal');
    let eventY = currentY + lineHeight * 8;

    this.analyticsEvents.slice(-50).forEach((event, index) => {
      const eventText = `${new Date(event.timestamp).toLocaleString()} - ${event.name}: ${JSON.stringify(event.data)}`;
      const lines = doc.splitTextToSize(eventText, pageWidth - margin * 2).lines;
      
      lines.forEach((line, i) => {
        if (i === 0) {
          doc.text(line, margin, eventY);
        } else {
          doc.text(line, margin, eventY + i * 4);
        }
      });
      
      eventY += lines.length * 4 + 2;
    });

    doc.save('challenges-analytics-report.pdf');
  }

  exportAnalyticsJSON() {
    const jsonContent = JSON.stringify({
      report: 'Challenges Dashboard Analytics',
      generated: new Date().toISOString(),
      dateRange: this.getDateRange(),
      summary: this.getEventsSummary(),
      events: this.analyticsEvents
    }, null, 2);

    const blob = new Blob([jsonContent], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `challenges-analytics-${new Date().toISOString().split('T')[0]}.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  exportAnalyticsCSV() {
    const summary = this.getEventsSummary();
    
    const headers = [
      'Event ID', 'Event Name', 'Timestamp', 'Session ID', 'Event Data'
    ];

    const rows = this.analyticsEvents.slice(-100).map(event => [
      event.id || '',
      event.name,
      new Date(event.timestamp).toISOString(),
      event.sessionId || '',
      JSON.stringify(event.data || {})
    ]);

    const csvContent = [
      headers.join(','),
      ...rows.map(row => row.join(','))
    ].join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `challenges-analytics-${new Date().toISOString().split('T')[0]}.csv`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  getDateRange() {
    if (this.analyticsEvents.length === 0) return 'No data';
    
    const timestamps = this.analyticsEvents.map(e => e.timestamp);
    const minTime = Math.min(...timestamps);
    const maxTime = Math.max(...timestamps);
    
    const startDate = new Date(minTime).toLocaleDateString();
    const endDate = new Date(maxTime).toLocaleDateString();
    
    return `${startDate} to ${endDate}`;
  }

  getEventsSummary() {
    const totalEvents = this.analyticsEvents.length;
    const pageViews = this.analyticsEvents.filter(e => e.name === 'page_view').length;
    const buttonClicks = this.analyticsEvents.filter(e => e.name === 'button_click').length;
    const refreshCount = this.analyticsEvents.filter(e => e.name === 'refresh_data').length;
    
    // Calculate average session duration
    const sessions = this.analyticsEvents.filter(e => e.name === 'page_visible');
    const avgSessionDuration = sessions.length > 0 
      ? sessions.reduce((sum, session) => sum + (session.data.timeSinceHidden || 0), 0) / sessions.length 
      : 0;

    return {
      totalEvents,
      pageViews,
      buttonClicks,
      refreshCount,
      avgSessionDuration
    };
  }
}